# Generated by Django 5.1 on 2024-09-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ID', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('religion', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('date_hired', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
