# Generated by Django 5.1.1 on 2024-09-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_logs', '0003_alter_member_image_attendancelog_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='logs'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
